workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Go to Flutter project folder
        script: |
          cd app

      - name: Flutter clean
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - app/build/app/outputs/flutter-apk/app-release.apk
